service: functions

provider:
  name: google
  stage: dev
  runtime: python37
  region: asia-northeast1
  project: ikedaosushi
  credentials: ~/.gcp/ikedaosushi-admin.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  hello:
    handler: hello
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: 'projects/${self:provider.project, ""}/topics/daily'
  test:
    handler: test
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: 'projects/${self:provider.project, ""}/topics/daily'
  list_compute:
    handler: list_compute
    events: 
      - http: path
