runtime: python
# runtime: custom
env: flex
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT app:app
# entrypoint: uwsgi ---http-socket :$PORT --wsgi-file app.py --callable app

runtime_config:
  python_version: 3

resources:
  cpu: 2
  memory_gb: 12
  disk_size_gb: 100

service:
  default

# env_variables:
#   REC_SYS_ENV: "dev"

# health_check:
#   enable_health_check: False

#readiness_check:
#  path: /readiness_check
#  app_start_timeout_sec: 300

# manual_scaling:
#   instances: 2

# endpoints_api_service:
#   # This is a template. Use the deploy_app.sh script to deploy this app.
#   name: SERVICE_NAME
#   config_id: SERVICE_CONFIG_ID
