FROM python:3.7

ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./

RUN pip install -r requirements.txt

# CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 app:app
CMD exec gunicorn --bind :80 --workers 1 --threads 8 app:app
# CMD exec uwsgi --http :80 --wsgi-file app.py --callable app